<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\TaskController:addAction' => function () {
    return ${($_ = isset($this->services['service_locator.yactgqk']) ? $this->services['service_locator.yactgqk'] : $this->load('getServiceLocator_YactgqkService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController:deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.kgsklev']) ? $this->services['service_locator.kgsklev'] : $this->load('getServiceLocator_KgsklevService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController:listAction' => function () {
    return ${($_ = isset($this->services['service_locator.bq0eyfj']) ? $this->services['service_locator.bq0eyfj'] : $this->load('getServiceLocator_Bq0eyfjService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController:updateAction' => function () {
    return ${($_ = isset($this->services['service_locator.nxernps']) ? $this->services['service_locator.nxernps'] : $this->load('getServiceLocator_NxernpsService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:addAction' => function () {
    return ${($_ = isset($this->services['service_locator.m33pmcd']) ? $this->services['service_locator.m33pmcd'] : $this->load('getServiceLocator_M33pmcdService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController::addAction' => function () {
    return ${($_ = isset($this->services['service_locator.yactgqk']) ? $this->services['service_locator.yactgqk'] : $this->load('getServiceLocator_YactgqkService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController::deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.kgsklev']) ? $this->services['service_locator.kgsklev'] : $this->load('getServiceLocator_KgsklevService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController::listAction' => function () {
    return ${($_ = isset($this->services['service_locator.bq0eyfj']) ? $this->services['service_locator.bq0eyfj'] : $this->load('getServiceLocator_Bq0eyfjService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController::updateAction' => function () {
    return ${($_ = isset($this->services['service_locator.nxernps']) ? $this->services['service_locator.nxernps'] : $this->load('getServiceLocator_NxernpsService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::addAction' => function () {
    return ${($_ = isset($this->services['service_locator.m33pmcd']) ? $this->services['service_locator.m33pmcd'] : $this->load('getServiceLocator_M33pmcdService.php')) && false ?: '_'};
})));
