<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.m33pmcd' shared service.

return $this->services['service_locator.m33pmcd'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('handler' => function () {
    $f = function (\AppBundle\Handler\AddUserHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Handler\AddUserHandler']) ? $this->services['AppBundle\Handler\AddUserHandler'] : $this->load('getAddUserHandlerService.php')) && false ?: '_'});
}));
