<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.yactgqk' shared service.

return $this->services['service_locator.yactgqk'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('handler' => function () {
    $f = function (\AppBundle\Handler\AddTaskHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Handler\AddTaskHandler']) ? $this->services['AppBundle\Handler\AddTaskHandler'] : $this->load('getAddTaskHandlerService.php')) && false ?: '_'});
}));
