<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.kgsklev' shared service.

return $this->services['service_locator.kgsklev'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('handler' => function () {
    $f = function (\AppBundle\Handler\DeleteTaskHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Handler\DeleteTaskHandler']) ? $this->services['AppBundle\Handler\DeleteTaskHandler'] : $this->load('getDeleteTaskHandlerService.php')) && false ?: '_'});
}));
