<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.zj3t5t2' shared service.

return $this->services['service_locator.zj3t5t2'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('taskLoader' => function () {
    $f = function (\AppBundle\Service\TaskLoader $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Service\TaskLoader']) ? $this->services['AppBundle\Service\TaskLoader'] : $this->load('getTaskLoaderService.php')) && false ?: '_'});
}));
