<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\TaskController:addAction' => function () {
    return ${($_ = isset($this->services['service_locator.e4nu7ta']) ? $this->services['service_locator.e4nu7ta'] : $this->load('getServiceLocator_E4nu7taService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController:checkAction' => function () {
    return ${($_ = isset($this->services['service_locator.zuflqdy']) ? $this->services['service_locator.zuflqdy'] : $this->load('getServiceLocator_ZuflqdyService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController:deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.poqs_hl']) ? $this->services['service_locator.poqs_hl'] : $this->load('getServiceLocator_PoqsHlService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController:listAction' => function () {
    return ${($_ = isset($this->services['service_locator.bq0eyfj']) ? $this->services['service_locator.bq0eyfj'] : $this->load('getServiceLocator_Bq0eyfjService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController:updateAction' => function () {
    return ${($_ = isset($this->services['service_locator.bqumobo']) ? $this->services['service_locator.bqumobo'] : $this->load('getServiceLocator_BqumoboService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController:updatePositionAction' => function () {
    return ${($_ = isset($this->services['service_locator.aeiuzpw']) ? $this->services['service_locator.aeiuzpw'] : $this->load('getServiceLocator_AeiuzpwService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:addAction' => function () {
    return ${($_ = isset($this->services['service_locator.f5_e11k']) ? $this->services['service_locator.f5_e11k'] : $this->load('getServiceLocator_F5E11kService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.3betdml']) ? $this->services['service_locator.3betdml'] : $this->load('getServiceLocator_3betdmlService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:listAction' => function () {
    return ${($_ = isset($this->services['service_locator._ld4n44']) ? $this->services['service_locator._ld4n44'] : $this->load('getServiceLocator_Ld4n44Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:updateAction' => function () {
    return ${($_ = isset($this->services['service_locator.8hkqyyo']) ? $this->services['service_locator.8hkqyyo'] : $this->load('getServiceLocator_8hkqyyoService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController::addAction' => function () {
    return ${($_ = isset($this->services['service_locator.e4nu7ta']) ? $this->services['service_locator.e4nu7ta'] : $this->load('getServiceLocator_E4nu7taService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController::checkAction' => function () {
    return ${($_ = isset($this->services['service_locator.zuflqdy']) ? $this->services['service_locator.zuflqdy'] : $this->load('getServiceLocator_ZuflqdyService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController::deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.poqs_hl']) ? $this->services['service_locator.poqs_hl'] : $this->load('getServiceLocator_PoqsHlService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController::listAction' => function () {
    return ${($_ = isset($this->services['service_locator.bq0eyfj']) ? $this->services['service_locator.bq0eyfj'] : $this->load('getServiceLocator_Bq0eyfjService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController::updateAction' => function () {
    return ${($_ = isset($this->services['service_locator.bqumobo']) ? $this->services['service_locator.bqumobo'] : $this->load('getServiceLocator_BqumoboService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\TaskController::updatePositionAction' => function () {
    return ${($_ = isset($this->services['service_locator.aeiuzpw']) ? $this->services['service_locator.aeiuzpw'] : $this->load('getServiceLocator_AeiuzpwService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::addAction' => function () {
    return ${($_ = isset($this->services['service_locator.f5_e11k']) ? $this->services['service_locator.f5_e11k'] : $this->load('getServiceLocator_F5E11kService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.3betdml']) ? $this->services['service_locator.3betdml'] : $this->load('getServiceLocator_3betdmlService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::listAction' => function () {
    return ${($_ = isset($this->services['service_locator._ld4n44']) ? $this->services['service_locator._ld4n44'] : $this->load('getServiceLocator_Ld4n44Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::updateAction' => function () {
    return ${($_ = isset($this->services['service_locator.8hkqyyo']) ? $this->services['service_locator.8hkqyyo'] : $this->load('getServiceLocator_8hkqyyoService.php')) && false ?: '_'};
})));
