<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.8hkqyyo' shared service.

return $this->services['service_locator.8hkqyyo'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('handler' => function () {
    $f = function (\AppBundle\Handler\UserUpdateHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Handler\UserUpdateHandler']) ? $this->services['AppBundle\Handler\UserUpdateHandler'] : $this->load('getUserUpdateHandlerService.php')) && false ?: '_'});
}));
