<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.nxernps' shared service.

return $this->services['service_locator.nxernps'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('handler' => function () {
    $f = function (\AppBundle\Handler\UpdateTaskHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Handler\UpdateTaskHandler']) ? $this->services['AppBundle\Handler\UpdateTaskHandler'] : $this->load('getUpdateTaskHandlerService.php')) && false ?: '_'});
}));
