<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.vylb4yj' shared service.

return $this->services['service_locator.vylb4yj'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('handler' => function () {
    $f = function (\AppBundle\Handler\UpdateTaskPositionHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Handler\UpdateTaskPositionHandler']) ? $this->services['AppBundle\Handler\UpdateTaskPositionHandler'] : $this->load('getUpdateTaskPositionHandlerService.php')) && false ?: '_'});
}));
