<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\EventListener\PositionTaskListener' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/EventListener/PositionTaskListener.php';
include_once $this->targetDirs[3].'/src/AppBundle/Service/PositionSorter.php';

return $this->services['AppBundle\EventListener\PositionTaskListener'] = new \AppBundle\EventListener\PositionTaskListener(new \AppBundle\Service\PositionSorter(), ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'});
