<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.aeiuzpw' shared service.

return $this->services['service_locator.aeiuzpw'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('handler' => function () {
    $f = function (\AppBundle\Handler\TaskUpdatePositionHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Handler\TaskUpdatePositionHandler']) ? $this->services['AppBundle\Handler\TaskUpdatePositionHandler'] : $this->load('getTaskUpdatePositionHandlerService.php')) && false ?: '_'});
}));
