<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.zuflqdy' shared service.

return $this->services['service_locator.zuflqdy'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('handler' => function () {
    $f = function (\AppBundle\Handler\TaskCheckHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Handler\TaskCheckHandler']) ? $this->services['AppBundle\Handler\TaskCheckHandler'] : $this->load('getTaskCheckHandlerService.php')) && false ?: '_'});
}));
