<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.3betdml' shared service.

return $this->services['service_locator.3betdml'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('handler' => function () {
    $f = function (\AppBundle\Handler\UserDeleteHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Handler\UserDeleteHandler']) ? $this->services['AppBundle\Handler\UserDeleteHandler'] : $this->load('getUserDeleteHandlerService.php')) && false ?: '_'});
}));
