<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.f5_e11k' shared service.

return $this->services['service_locator.f5_e11k'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('handler' => function () {
    $f = function (\AppBundle\Handler\UserAddHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Handler\UserAddHandler']) ? $this->services['AppBundle\Handler\UserAddHandler'] : $this->load('getUserAddHandlerService.php')) && false ?: '_'});
}));
