<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.laowypj' shared service.

return $this->services['service_locator.laowypj'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('taskSessionHandler' => function () {
    $f = function (\AppBundle\Service\TaskSessionHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Service\TaskSessionHandler']) ? $this->services['AppBundle\Service\TaskSessionHandler'] : $this->load('getTaskSessionHandlerService.php')) && false ?: '_'});
}));
