<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.e4nu7ta' shared service.

return $this->services['service_locator.e4nu7ta'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('handler' => function () {
    $f = function (\AppBundle\Handler\TaskAddHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Handler\TaskAddHandler']) ? $this->services['AppBundle\Handler\TaskAddHandler'] : $this->load('getTaskAddHandlerService.php')) && false ?: '_'});
}, 'manager' => function () {
    return ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'};
}));
