<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.bqumobo' shared service.

return $this->services['service_locator.bqumobo'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('handler' => function () {
    $f = function (\AppBundle\Handler\TaskUpdateHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Handler\TaskUpdateHandler']) ? $this->services['AppBundle\Handler\TaskUpdateHandler'] : $this->load('getTaskUpdateHandlerService.php')) && false ?: '_'});
}));
