<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.poqs_hl' shared service.

return $this->services['service_locator.poqs_hl'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('handler' => function () {
    $f = function (\AppBundle\Handler\TaskDeleteHandler $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Handler\TaskDeleteHandler']) ? $this->services['AppBundle\Handler\TaskDeleteHandler'] : $this->load('getTaskDeleteHandlerService.php')) && false ?: '_'});
}));
