<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX1pkjzb\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX1pkjzb/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX1pkjzb.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX1pkjzb\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerX1pkjzb\appTestDebugProjectContainer(array(
    'container.build_hash' => 'X1pkjzb',
    'container.build_id' => '846b521c',
    'container.build_time' => 1543364877,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX1pkjzb');
