<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF78kgec\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF78kgec/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerF78kgec.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerF78kgec\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerF78kgec\appDevDebugProjectContainer(array(
    'container.build_hash' => 'F78kgec',
    'container.build_id' => 'f18feafd',
    'container.build_time' => 1543362850,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerF78kgec');
