<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWuvag4d\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWuvag4d/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWuvag4d.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWuvag4d\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWuvag4d\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Wuvag4d',
    'container.build_id' => 'be1a305f',
    'container.build_time' => 1543358071,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWuvag4d');
