<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKc5itc4\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKc5itc4/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKc5itc4.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKc5itc4\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKc5itc4\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kc5itc4',
    'container.build_id' => 'f90f45c5',
    'container.build_time' => 1539889388,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKc5itc4');
